---
platforms:
  - &platform-basic
    name: molecule-docker-ingress-el8-${CI_JOB_ID:-1}
    image: centos:8
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    stop_signal: "SIGRTMIN+3"
    privileged: true
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For dockerd
      - SYS_RESOURCE  # For dockerd oom_score_adj
  - <<: *platform-basic
    name: molecule-docker-ingress-el7-${CI_JOB_ID:-1}
    image: centos:7
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-docker-ingress-el8-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python3
      molecule-docker-ingress-el7-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
verifier:
  name: testinfra
  options:
    verbose: true
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8
