---
version: '3.7'

x-container: &container
  restart: always
  logging:
    options:
      max-size: "200k"
      max-file: "10"

services:
  docker-gen:
    <<: *container
    image: ${DOCKER_GEN__IMAGE_NAME:-jwilder/docker-gen}:${DOCKER_GEN__IMAGE_TAG:-0.7.3}
    network_mode: host
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      VIRTUAL_DEFAULT_LISTEN_HTTP_PORT: ${VIRTUAL_DEFAULT_LISTEN_HTTP_PORT:-80}
      VIRTUAL_DEFAULT_LISTEN_HTTPS_PORT: ${VIRTUAL_DEFAULT_LISTEN_HTTPS_PORT:-443}
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    command:
      - -notify-sighup
      - ingress-nginx  # must be equal container_name: ingress-nginx
      - -watch
      - /etc/docker-gen/templates/nginx.tmpl
      - /etc/nginx/conf.d/default.conf
    volumes:
      - ./volumes/docker-gen/templates:/etc/docker-gen/templates:ro
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - vhost.d:/etc/nginx/vhost.d

  nginx:
    <<: *container
    image: ${NGINX__IMAGE_NAME:-nginx}:${NGINX__IMAGE_TAG:-1.18-alpine}
    container_name: ingress-nginx
    network_mode: host
    volumes:
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

  letsencrypt:
    <<: *container
    image: ${LETSENCRYPT_NGINX_PROXY_COMPANION__IMAGE_NAME:-jrcs/letsencrypt-nginx-proxy-companion}:${LETSENCRYPT_NGINX_PROXY_COMPANION__IMAGE_TAG:-v1.12.1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
    depends_on:
      - docker-gen
      - nginx

volumes:
  certs:
  conf.d:
  dhparam:
  html:
  vhost.d:
